graphqlUrl: /it-graphql-ita/
signalrUrl: https://m.it.ua/ws/signalr/hubs
siteUrl: https://m.it.ua
webServiceUrl: https://m.it.ua
iconset: ""
rtl: ""
scaling:
  replicas: 1 #3
  affinity:
    enableNodeAntiAfinity: false #true
    nodeLabelSelector: "" #dep: itenterprise
resources:
  requests:
    cpu: "20m"
    memory: "30Mi"
  limits:
    cpu: "1"
    memory: "4Gi"
DepSettings:
  Namespace:
  NodeSelector: { }  #dep: itenterprise
  OuterClusterRoot:
  Tolerations: []
