query allConditionParameters($after: String, $first: Int, $where: [WhereExpressionGraph], $orderBy: [OrderByGraph], $ids: [ID]) {
  eam {
    conditionParametersConnection(after: $after, first: $first, where: $where, orderBy: $orderBy, ids: $ids) {
      edges {
        node {
          id
          name
          measurementUnit {
            id
            name
          }
          minValue
          maxValue
          conditionParameterType {
            id
            name
          }
          period
          valueInputType
          isValid
        }
      }
      totalCount
      pageInfo {
        hasNextPage
        hasPreviousPage
        startCursor
        endCursor
      }
    }
  }
}