stages:
  - build
  - publish
  - publish_SP

build_smartManager:
    stage: build
    tags:
      - tfs2017 
    script:
      - 'npm install'
      - 'npm run build'
      - 'dir'
    cache:
      key: dist
      paths:
        - dist
      policy: push

publish_smartManager:
    stage: publish
    tags:
      - tfs2017 
    script:
    - 'xcopy /S /E ".\dist\*" "\\it.ua\dfs\private\Bakharev\sm\publish"'
    #rules:
    #- if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    cache:
      key: dist
      paths:
        - dist
      policy: pull

publish_smartManager_SP:
    stage: publish_SP
    tags:
    - tfs2017 
    script:
      - 'mkdir \\it.ua\dfs\private\Bakharev\sm\$CI_COMMIT_REF_NAME'
      - 'xcopy /S /E ".\dist\*" "\\it.ua\dfs\private\Bakharev\sm\$CI_COMMIT_REF_NAME"'
    rules:
      - if: '$CI_COMMIT_REF_NAME != "master"'
        when: manual
    cache:
      key: dist
      paths:
        - dist
      policy: pull