variables:
  NUGET_PATH: 'C:\Program Files (x86)\NuGet\nuget.exe'
  MSBUILD_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe'
  DOTNET_PUBLISH: 'C:\Program Files\dotnet.exe publish'
stages:
  - build
  - deploy

build_job:
    stage: build
    tags:
    - tfs2017 
    script:
    - 'cd .\RichEdit\RichEdit_Viewer'
    - '& "$env:NUGET_PATH" restore RichEdit_Viewer.sln'
    - '& "$env:MSBUILD_PATH" /p:Configuration=Release /p:VisualStudioVersion=19.0 RichEdit_Viewer.sln'
    - '& "$env:MSBUILD_PATH" RichEdit_Viewer\RichEdit_Viewer.csproj /p:DeployOnBuild=true /p:Configuration=Release /P:PublishProfile=FolderProfile.pubxml'
    when: always
    
deploy_job:
    stage: deploy
    tags:
    - tfs2017
    script:
    - echo $env:CURRENT_PATH
    - 'cd .\RichEdit\RichEdit_Viewer\RichEdit_Viewer'
    - 'dir'
