stages:
  - build
  - publish
  - publish_SP

build_smartManager:
    stage: build
    tags:
      - tfs2017 
    script:
      - 'npm install'
      - 'npm run build'
      - 'dir'
    cache:
      key: $CI_COMMIT_REF_NAME
      paths:
        - dist
      policy: push

publish_smartManager:
    stage: publish
    tags:
      - tfs2017 
    only: 
      - master/@it-enterprise/web-apps/smartmanager-web
    script:
    - 'xcopy /S /E /Y ".\dist\*" "\\it.ua\dfs\private\Bakharev\sm\publish"'
    #rules:
    #- if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    cache:
      key: $CI_COMMIT_REF_NAME
      paths:
        - dist
      policy: pull

publish_smartManager_SP:
    stage: publish_SP
    tags:
    - tfs2017 
    script:
      - 'mkdir -p \\it.ua\dfs\private\Bakharev\sm\$CI_COMMIT_REF_NAME'
      - 'xcopy /S /E /Y".\dist\*" "\\it.ua\dfs\private\Bakharev\sm\$CI_COMMIT_REF_NAME"'
    only:
      - /^202*/@it-enterprise/web-apps/smartmanager-web

    cache:
      key: $CI_COMMIT_REF_NAME
      paths:
        - dist
      policy: pull