apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-smartmanager
  labels:
    apps: {{ .Release.Name }}
    release: {{ .Release.Name }}
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: {{ .Release.Name }}-smartmanager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-smartmanager
  labels:
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.scaling.replicas | default 1 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-smartmanager
  template:
    metadata:
      name: stock-app
      labels:
        app: {{ .Release.Name }}-smartmanager
        release: {{ .Release.Name }}
      namespace: m1itent
    spec:
      containers:
      - name: engine
        image: m1itent.azurecr.io/it/smartmanager:{{ .Chart.AppVersion }}
        env:
        - name: APP_VERSION
          value: "{{ .Chart.AppVersion }}"
        - name: VUE_APP_BASE_PATH
          value: "/{{ .Release.Name }}/"
        - name: NODE_ENV
          value: "production"
        command: ["/bin/sh"]
        args: ["-c","find ./app -type f -exec sed -i 's/\\/webapps\\//\\/{{ .Release.Name }}\\//g' {} +; find ./app  -type f -exec sed -i 's/\\*GRAPHQLURL\\*/{{ regexReplaceAll "\\W" .Values.graphqlUrl "\\\\${0}" }}/g' {} + ; find ./app  -type f -exec sed -i 's/\\*SIGNALRURL\\*/{{ regexReplaceAll "\\W" .Values.signalrUrl  "\\\\${0}"  }}/g' {} + ; find ./app  -type f -exec sed -i 's/\\*WEBSERVICEURL\\*/{{ regexReplaceAll "\\W" .Values.webServiceUrl  "\\\\${0}"  }}/g' {} + ; find ./app  -type f -exec sed -i 's/\\*SITEURL\\*/{{ regexReplaceAll "\\W" .Values.siteUrl  "\\\\${0}"  }}/g' {} + ; nginx -g 'daemon off;'"]
        #command: ["find . -type f -exec sed -i 's/\\/zzz\\//\\/{{ .Values.graphql }}\\//g' {} +"]
        # args: ["APP_VERSION=$(APP_VERSION) VUE_APP_BASE_PATH=$(VUE_APP_BASE_PATH) VUE_APP_GRAPHQL_PATH=$(VUE_APP_GRAPHQL_PATH) NODE_ENV=$(NODE_ENV) BASE_URL=$(BASE_URL)"]
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        ports:
          - containerPort: 80
      {{- if .Values.scaling.affinity.enableNodeAntiAfinity }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                app: {{ .Release.Name }}-smartmanager
      {{- end }}
      imagePullSecrets:
      - name: m1itent-reader
      nodeSelector:
        dep: m1itent
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /{{ .Release.Name }}(/|$)(.*)
        backend:
          serviceName: {{ .Release.Name }}-smartmanager
          servicePort: 80
