<template>
  <formio id="formio" class="formio-container" :form='myform' v-on:submit="onSubmit()"></formio>
</template>
<script>
import {mapGetters} from 'vuex'
import { Form } from '../../../../node_modules/vue-formio';


export default {
    data(){
      var myform = 	 {"components": [
		{
			"label": "Tabs",
			"components": [
				{
					"label": "Production",
					"key": "tab2",
					"components": [
						{
							"label": "Columns",
							"columns": [
								{
									"components": [
										{
											"label": "Prodused",
											"mask": false,
											"tableView": true,
											"alwaysEnabled": false,
											"type": "number",
											"input": true,
											"key": "vyrabotka",
											"validate": {
												"customMessage": "",
												"json": "",
												"required": false,
												"custom": "",
												"customPrivate": false,
												"min": "",
												"max": "",
												"step": "any",
												"integer": ""
											},
											"conditional": {
												"show": "",
												"when": "",
												"json": "",
												"eq": ""
											},
											"delimiter": false,
											"requireDecimal": false,
											"encrypted": false,
											"properties": {},
											"customConditional": "",
											"logic": [
												{
													"name": "add1",
													"trigger": {
														"type": "event",
														"event": "add1"
													},
													"actions": [
														{
															"name": "add1",
															"type": "value",
															"value": "value = value ? value + 1 : 1;"
														}
													]
												},
												{
													"name": "add4",
													"trigger": {
														"type": "event",
														"event": "add4"
													},
													"actions": [
														{
															"name": "add4",
															"type": "value",
															"value": "value = value ? value + 4 : 4;"
														}
													]
												},
												{
													"name": "add10",
													"trigger": {
														"type": "event",
														"event": "add10"
													},
													"actions": [
														{
															"name": "add10",
															"type": "value",
															"value": "value = value ? value + 10 : 10;"
														}
													]
												}
											],
											"attributes": {},
											"reorder": false,
											"placeholder": "",
											"prefix": "",
											"customClass": "",
											"suffix": "",
											"multiple": false,
											"defaultValue": null,
											"protected": false,
											"unique": false,
											"persistent": true,
											"hidden": false,
											"clearOnHide": true,
											"dataGridLabel": false,
											"labelPosition": "top",
											"labelWidth": 30,
											"labelMargin": 3,
											"description": "",
											"errorLabel": "",
											"tooltip": "",
											"hideLabel": false,
											"tabindex": "",
											"disabled": false,
											"autofocus": false,
											"dbIndex": false,
											"customDefaultValue": "",
											"calculateValue": "",
											"allowCalculateOverride": false,
											"widget": null,
											"refreshOn": "",
											"clearOnRefresh": false,
											"validateOn": "change",
											"id": "e9chyap"
										},
										{
											"label": "Columns",
											"columns": [
												{
													"components": [
														{
															"label": "+1",
															"action": "event",
															"state": "",
															"showValidations": false,
															"event": "add1",
															"shortcut": "",
															"mask": false,
															"autofocus": true,
															"tableView": true,
															"alwaysEnabled": false,
															"type": "button",
															"input": true,
															"key": "1",
															"defaultValue": false,
															"validate": {
																"customMessage": "",
																"json": "",
																"required": false,
																"custom": "",
																"customPrivate": false
															},
															"conditional": {
																"show": "",
																"when": "",
																"json": "",
																"eq": ""
															},
															"encrypted": false,
															"properties": {},
															"customConditional": "",
															"logic": [],
															"attributes": {},
															"url": "",
															"custom": "",
															"reorder": false,
															"placeholder": "",
															"prefix": "",
															"customClass": "",
															"suffix": "",
															"multiple": false,
															"protected": false,
															"unique": false,
															"persistent": false,
															"hidden": false,
															"clearOnHide": true,
															"dataGridLabel": true,
															"labelPosition": "top",
															"labelWidth": 30,
															"labelMargin": 3,
															"description": "",
															"errorLabel": "",
															"tooltip": "",
															"hideLabel": false,
															"tabindex": "",
															"disabled": false,
															"dbIndex": false,
															"customDefaultValue": "",
															"calculateValue": "",
															"allowCalculateOverride": false,
															"widget": null,
															"refreshOn": "",
															"clearOnRefresh": false,
															"validateOn": "change",
															"size": "md",
															"leftIcon": "",
															"rightIcon": "",
															"block": false,
															"disableOnInvalid": false,
															"theme": "default",
															"id": "erix6f"
														}
													],
													"width": 4,
													"offset": 0,
													"push": 0,
													"pull": 0,
													"type": "column",
													"input": false,
													"hideOnChildrenHidden": false,
													"key": "column",
													"tableView": true,
													"label": "Column",
													"placeholder": "",
													"prefix": "",
													"customClass": "",
													"suffix": "",
													"multiple": false,
													"defaultValue": null,
													"protected": false,
													"unique": false,
													"persistent": true,
													"hidden": false,
													"clearOnHide": true,
													"dataGridLabel": false,
													"labelPosition": "top",
													"labelWidth": 30,
													"labelMargin": 3,
													"description": "",
													"errorLabel": "",
													"tooltip": "",
													"hideLabel": false,
													"tabindex": "",
													"disabled": false,
													"autofocus": false,
													"dbIndex": false,
													"customDefaultValue": "",
													"calculateValue": "",
													"allowCalculateOverride": false,
													"widget": null,
													"refreshOn": "",
													"clearOnRefresh": false,
													"validateOn": "change",
													"validate": {
														"required": false,
														"custom": "",
														"customPrivate": false
													},
													"conditional": {
														"show": null,
														"when": null,
														"eq": ""
													},
													"id": "ei116q"
												},
												{
													"components": [
														{
															"label": "+4",
															"action": "event",
															"state": "",
															"shortcut": "",
															"mask": false,
															"tableView": true,
															"alwaysEnabled": false,
															"type": "button",
															"input": true,
															"key": "4",
															"defaultValue": false,
															"validate": {
																"customMessage": "",
																"json": "",
																"required": false,
																"custom": "",
																"customPrivate": false
															},
															"conditional": {
																"show": "",
																"when": "",
																"json": "",
																"eq": ""
															},
															"encrypted": false,
															"properties": {},
															"customConditional": "",
															"logic": [],
															"attributes": {},
															"showValidations": false,
															"event": "add4",
															"url": "",
															"custom": "",
															"reorder": false,
															"placeholder": "",
															"prefix": "",
															"customClass": "",
															"suffix": "",
															"multiple": false,
															"protected": false,
															"unique": false,
															"persistent": false,
															"hidden": false,
															"clearOnHide": true,
															"dataGridLabel": true,
															"labelPosition": "top",
															"labelWidth": 30,
															"labelMargin": 3,
															"description": "",
															"errorLabel": "",
															"tooltip": "",
															"hideLabel": false,
															"tabindex": "",
															"disabled": false,
															"autofocus": false,
															"dbIndex": false,
															"customDefaultValue": "",
															"calculateValue": "",
															"allowCalculateOverride": false,
															"widget": null,
															"refreshOn": "",
															"clearOnRefresh": false,
															"validateOn": "change",
															"size": "md",
															"leftIcon": "",
															"rightIcon": "",
															"block": false,
															"disableOnInvalid": false,
															"theme": "default",
															"id": "eb6io8"
														}
													],
													"width": 4,
													"offset": 0,
													"push": 0,
													"pull": 0,
													"type": "column",
													"input": false,
													"hideOnChildrenHidden": false,
													"key": "column",
													"tableView": true,
													"label": "Column",
													"placeholder": "",
													"prefix": "",
													"customClass": "",
													"suffix": "",
													"multiple": false,
													"defaultValue": null,
													"protected": false,
													"unique": false,
													"persistent": true,
													"hidden": false,
													"clearOnHide": true,
													"dataGridLabel": false,
													"labelPosition": "top",
													"labelWidth": 30,
													"labelMargin": 3,
													"description": "",
													"errorLabel": "",
													"tooltip": "",
													"hideLabel": false,
													"tabindex": "",
													"disabled": false,
													"autofocus": false,
													"dbIndex": false,
													"customDefaultValue": "",
													"calculateValue": "",
													"allowCalculateOverride": false,
													"widget": null,
													"refreshOn": "",
													"clearOnRefresh": false,
													"validateOn": "change",
													"validate": {
														"required": false,
														"custom": "",
														"customPrivate": false
													},
													"conditional": {
														"show": null,
														"when": null,
														"eq": ""
													},
													"id": "edsbzgc"
												},
												{
													"width": 4,
													"offset": 0,
													"push": 0,
													"pull": 0,
													"type": "column",
													"input": false,
													"hideOnChildrenHidden": false,
													"key": "column",
													"tableView": true,
													"label": "Column",
													"components": [
														{
															"label": "+10",
															"action": "event",
															"state": "add10",
															"shortcut": "",
															"mask": false,
															"tableView": true,
															"alwaysEnabled": false,
															"type": "button",
															"input": true,
															"key": "10",
															"defaultValue": false,
															"validate": {
																"customMessage": "",
																"json": "",
																"required": false,
																"custom": "",
																"customPrivate": false
															},
															"conditional": {
																"show": "",
																"when": "",
																"json": "",
																"eq": ""
															},
															"encrypted": false,
															"properties": {},
															"customConditional": "",
															"logic": [],
															"attributes": {},
															"showValidations": false,
															"event": "",
															"url": "",
															"custom": "",
															"reorder": false,
															"placeholder": "",
															"prefix": "",
															"customClass": "",
															"suffix": "",
															"multiple": false,
															"protected": false,
															"unique": false,
															"persistent": false,
															"hidden": false,
															"clearOnHide": true,
															"dataGridLabel": true,
															"labelPosition": "top",
															"labelWidth": 30,
															"labelMargin": 3,
															"description": "",
															"errorLabel": "",
															"tooltip": "",
															"hideLabel": false,
															"tabindex": "",
															"disabled": false,
															"autofocus": false,
															"dbIndex": false,
															"customDefaultValue": "",
															"calculateValue": "",
															"allowCalculateOverride": false,
															"widget": null,
															"refreshOn": "",
															"clearOnRefresh": false,
															"validateOn": "change",
															"size": "md",
															"leftIcon": "",
															"rightIcon": "",
															"block": false,
															"disableOnInvalid": false,
															"theme": "default",
															"id": "e6y8ssb"
														}
													],
													"placeholder": "",
													"prefix": "",
													"customClass": "",
													"suffix": "",
													"multiple": false,
													"defaultValue": null,
													"protected": false,
													"unique": false,
													"persistent": true,
													"hidden": false,
													"clearOnHide": true,
													"dataGridLabel": false,
													"labelPosition": "top",
													"labelWidth": 30,
													"labelMargin": 3,
													"description": "",
													"errorLabel": "",
													"tooltip": "",
													"hideLabel": false,
													"tabindex": "",
													"disabled": false,
													"autofocus": false,
													"dbIndex": false,
													"customDefaultValue": "",
													"calculateValue": "",
													"allowCalculateOverride": false,
													"widget": null,
													"refreshOn": "",
													"clearOnRefresh": false,
													"validateOn": "change",
													"validate": {
														"required": false,
														"custom": "",
														"customPrivate": false
													},
													"conditional": {
														"show": null,
														"when": null,
														"eq": ""
													},
													"id": "enc03gb"
												}
											],
											"mask": false,
											"tableView": false,
											"alwaysEnabled": false,
											"type": "columns",
											"input": false,
											"key": "columns",
											"conditional": {
												"show": "",
												"when": "",
												"json": "",
												"eq": ""
											},
											"properties": {},
											"customConditional": "",
											"logic": [],
											"attributes": {},
											"reorder": false,
											"placeholder": "",
											"prefix": "",
											"customClass": "",
											"suffix": "",
											"multiple": false,
											"defaultValue": null,
											"protected": false,
											"unique": false,
											"persistent": false,
											"hidden": false,
											"clearOnHide": false,
											"dataGridLabel": false,
											"labelPosition": "top",
											"labelWidth": 30,
											"labelMargin": 3,
											"description": "",
											"errorLabel": "",
											"tooltip": "",
											"hideLabel": false,
											"tabindex": "",
											"disabled": false,
											"autofocus": false,
											"dbIndex": false,
											"customDefaultValue": "",
											"calculateValue": "",
											"allowCalculateOverride": false,
											"widget": null,
											"refreshOn": "",
											"clearOnRefresh": false,
											"validateOn": "change",
											"validate": {
												"required": false,
												"custom": "",
												"customPrivate": false
											},
											"autoAdjust": false,
											"hideOnChildrenHidden": false,
											"id": "ev1hk0q"
										}
									],
									"width": 4,
									"offset": 0,
									"push": 0,
									"pull": 0,
									"type": "column",
									"input": false,
									"hideOnChildrenHidden": false,
									"key": "column",
									"tableView": true,
									"label": "Column",
									"placeholder": "",
									"prefix": "",
									"customClass": "",
									"suffix": "",
									"multiple": false,
									"defaultValue": null,
									"protected": false,
									"unique": false,
									"persistent": true,
									"hidden": false,
									"clearOnHide": true,
									"dataGridLabel": false,
									"labelPosition": "top",
									"labelWidth": 30,
									"labelMargin": 3,
									"description": "",
									"errorLabel": "",
									"tooltip": "",
									"hideLabel": false,
									"tabindex": "",
									"disabled": false,
									"autofocus": false,
									"dbIndex": false,
									"customDefaultValue": "",
									"calculateValue": "",
									"allowCalculateOverride": false,
									"widget": null,
									"refreshOn": "",
									"clearOnRefresh": false,
									"validateOn": "change",
									"validate": {
										"required": false,
										"custom": "",
										"customPrivate": false
									},
									"conditional": {
										"show": null,
										"when": null,
										"eq": ""
									},
									"id": "ehpzdnh"
								},
								{
									"components": [
										{
											"label": "Fix Defect Count",
											"mask": false,
											"disabled": true,
											"tableView": true,
											"alwaysEnabled": false,
											"type": "number",
											"input": true,
											"key": "fixDefects",
											"validate": {
												"customMessage": "",
												"json": "",
												"required": false,
												"custom": "",
												"customPrivate": false,
												"min": "",
												"max": "",
												"step": "any",
												"integer": ""
											},
											"conditional": {
												"show": "",
												"when": "",
												"json": "",
												"eq": ""
											},
											"delimiter": false,
											"requireDecimal": false,
											"encrypted": false,
											"properties": {},
											"customConditional": "",
											"logic": [],
											"attributes": {},
											"calculateValue": "value = data.defectItems.length;",
											"tags": [],
											"reorder": false,
											"placeholder": "",
											"prefix": "",
											"customClass": "",
											"suffix": "",
											"multiple": false,
											"defaultValue": null,
											"protected": false,
											"unique": false,
											"persistent": true,
											"hidden": false,
											"clearOnHide": true,
											"dataGridLabel": false,
											"labelPosition": "top",
											"labelWidth": 30,
											"labelMargin": 3,
											"description": "",
											"errorLabel": "",
											"tooltip": "",
											"hideLabel": false,
											"tabindex": "",
											"autofocus": false,
											"dbIndex": false,
											"customDefaultValue": "",
											"allowCalculateOverride": false,
											"widget": null,
											"refreshOn": "",
											"clearOnRefresh": false,
											"validateOn": "change",
											"id": "eyd3m0k"
										}
									],
									"width": 4,
									"offset": 0,
									"push": 0,
									"pull": 0,
									"type": "column",
									"input": false,
									"hideOnChildrenHidden": false,
									"key": "column",
									"tableView": true,
									"label": "Column",
									"placeholder": "",
									"prefix": "",
									"customClass": "",
									"suffix": "",
									"multiple": false,
									"defaultValue": null,
									"protected": false,
									"unique": false,
									"persistent": true,
									"hidden": false,
									"clearOnHide": true,
									"dataGridLabel": false,
									"labelPosition": "top",
									"labelWidth": 30,
									"labelMargin": 3,
									"description": "",
									"errorLabel": "",
									"tooltip": "",
									"hideLabel": false,
									"tabindex": "",
									"disabled": false,
									"autofocus": false,
									"dbIndex": false,
									"customDefaultValue": "",
									"calculateValue": "",
									"allowCalculateOverride": false,
									"widget": null,
									"refreshOn": "",
									"clearOnRefresh": false,
									"validateOn": "change",
									"validate": {
										"required": false,
										"custom": "",
										"customPrivate": false
									},
									"conditional": {
										"show": null,
										"when": null,
										"eq": ""
									},
									"id": "e9pl5h"
								},
								{
									"width": 4,
									"offset": 0,
									"push": 0,
									"pull": 0,
									"type": "column",
									"input": false,
									"hideOnChildrenHidden": false,
									"key": "column",
									"tableView": true,
									"label": "Column",
									"components": [
										{
											"label": "NoFix Defect Count",
											"mask": false,
											"disabled": true,
											"tableView": true,
											"alwaysEnabled": false,
											"type": "number",
											"input": true,
											"key": "noFixDefects",
											"validate": {
												"customMessage": "",
												"json": "",
												"required": false,
												"custom": "",
												"customPrivate": false,
												"min": "",
												"max": "",
												"step": "any",
												"integer": ""
											},
											"conditional": {
												"show": "",
												"when": "",
												"json": "",
												"eq": ""
											},
											"delimiter": false,
											"requireDecimal": false,
											"encrypted": false,
											"properties": {},
											"customConditional": "",
											"logic": [],
											"attributes": {},
											"tags": [],
											"calculateValue": "value = data.defectItems.length;",
											"reorder": false,
											"placeholder": "",
											"prefix": "",
											"customClass": "",
											"suffix": "",
											"multiple": false,
											"defaultValue": null,
											"protected": false,
											"unique": false,
											"persistent": true,
											"hidden": false,
											"clearOnHide": true,
											"dataGridLabel": false,
											"labelPosition": "top",
											"labelWidth": 30,
											"labelMargin": 3,
											"description": "",
											"errorLabel": "",
											"tooltip": "",
											"hideLabel": false,
											"tabindex": "",
											"autofocus": false,
											"dbIndex": false,
											"customDefaultValue": "",
											"allowCalculateOverride": false,
											"widget": null,
											"refreshOn": "",
											"clearOnRefresh": false,
											"validateOn": "change",
											"id": "eina23"
										}
									],
									"placeholder": "",
									"prefix": "",
									"customClass": "",
									"suffix": "",
									"multiple": false,
									"defaultValue": null,
									"protected": false,
									"unique": false,
									"persistent": true,
									"hidden": false,
									"clearOnHide": true,
									"dataGridLabel": false,
									"labelPosition": "top",
									"labelWidth": 30,
									"labelMargin": 3,
									"description": "",
									"errorLabel": "",
									"tooltip": "",
									"hideLabel": false,
									"tabindex": "",
									"disabled": false,
									"autofocus": false,
									"dbIndex": false,
									"customDefaultValue": "",
									"calculateValue": "",
									"allowCalculateOverride": false,
									"widget": null,
									"refreshOn": "",
									"clearOnRefresh": false,
									"validateOn": "change",
									"validate": {
										"required": false,
										"custom": "",
										"customPrivate": false
									},
									"conditional": {
										"show": null,
										"when": null,
										"eq": ""
									},
									"id": "esf2ie9"
								}
							],
							"mask": false,
							"tableView": false,
							"alwaysEnabled": false,
							"type": "columns",
							"input": false,
							"key": "columns4",
							"conditional": {
								"show": "",
								"when": "",
								"json": "",
								"eq": ""
							},
							"properties": {},
							"customConditional": "",
							"logic": [],
							"attributes": {},
							"tab": 0,
							"reorder": false,
							"placeholder": "",
							"prefix": "",
							"customClass": "",
							"suffix": "",
							"multiple": false,
							"defaultValue": null,
							"protected": false,
							"unique": false,
							"persistent": false,
							"hidden": false,
							"clearOnHide": false,
							"dataGridLabel": false,
							"labelPosition": "top",
							"labelWidth": 30,
							"labelMargin": 3,
							"description": "",
							"errorLabel": "",
							"tooltip": "",
							"hideLabel": false,
							"tabindex": "",
							"disabled": false,
							"autofocus": false,
							"dbIndex": false,
							"customDefaultValue": "",
							"calculateValue": "",
							"allowCalculateOverride": false,
							"widget": null,
							"refreshOn": "",
							"clearOnRefresh": false,
							"validateOn": "change",
							"validate": {
								"required": false,
								"custom": "",
								"customPrivate": false
							},
							"autoAdjust": false,
							"hideOnChildrenHidden": false,
							"id": "eiyictb"
						},
						{
							"label": "Quality Info",
							"disableAddingRemovingRows": true,
							"defaultOpen": false,
							"layoutFixed": false,
							"enableRowGroups": false,
							"reorder": false,
							"mask": false,
							"tableView": true,
							"alwaysEnabled": false,
							"type": "datagrid",
							"input": true,
							"key": "kachInfo",
							"defaultValue": [
								{
									"charactName": "Diameter",
									"need": 50,
									"fact": 5,
									"perc": 10
								},
								{
									"charactName": "Tolschina",
									"need": 20,
									"fact": 5,
									"perc": 25
								}
							],
							"validate": {
								"customMessage": "",
								"json": "",
								"required": false,
								"custom": "",
								"customPrivate": false
							},
							"conditional": {
								"show": "",
								"when": "",
								"json": "",
								"eq": ""
							},
							"components": [
							{
									"label": "Characteristic Name",
									"allowMultipleMasks": false,
									"showWordCount": false,
									"showCharCount": false,
									"disabled": true,
									"tableView": true,
									"alwaysEnabled": false,
									"type": "textfield",
									"input": true,
									"key": "charactName",
									"defaultValue": "",
									"validate": {
										"customMessage": "",
										"json": "",
										"required": false,
										"custom": "",
										"customPrivate": false,
										"minLength": "",
										"maxLength": "",
										"minWords": "",
										"maxWords": "",
										"pattern": ""
									},
									"conditional": {
										"show": "",
										"when": "",
										"json": "",
										"eq": ""
									},
									"inputFormat": "plain",
									"encrypted": false,
									"properties": {},
									"customConditional": "",
									"logic": [],
									"attributes": {},
									"row": "0-3",
									"widget": {
										"type": "",
										"format": "yyyy-MM-dd hh:mm a",
										"dateFormat": "yyyy-MM-dd hh:mm a",
										"saveAs": "text"
									},
									"reorder": false
								},
								{
									"label": "Plan",
									"mask": false,
									"disabled": true,
									"tableView": true,
									"alwaysEnabled": false,
									"type": "number",
									"input": true,
									"key": "need",
									"validate": {
										"customMessage": "",
										"json": "",
										"required": false,
										"custom": "",
										"customPrivate": false,
										"min": "",
										"max": "",
										"step": "any",
										"integer": ""
									},
									"conditional": {
										"show": "",
										"when": "",
										"json": "",
										"eq": ""
									},
									"delimiter": false,
									"requireDecimal": false,
									"encrypted": false,
									"properties": {},
									"customConditional": "",
									"logic": [],
									"attributes": {},
									"row": "0-0",
									"reorder": false
								},
								{
									"label": "Fact",
									"mask": false,
									"disabled": true,
									"tableView": true,
									"alwaysEnabled": false,
									"type": "number",
									"input": true,
									"key": "fact",
									"validate": {
										"customMessage": "",
										"json": "",
										"required": false,
										"custom": "",
										"customPrivate": false,
										"min": "",
										"max": "",
										"step": "any",
										"integer": ""
									},
									"conditional": {
										"show": "",
										"when": "",
										"json": "",
										"eq": ""
									},
									"delimiter": false,
									"requireDecimal": false,
									"encrypted": false,
									"properties": {},
									"customConditional": "",
									"logic": [],
									"attributes": {},
									"row": "0-1",
									"reorder": false
								},
								{
									"label": "%",
									"mask": false,
									"disabled": true,
									"tableView": true,
									"alwaysEnabled": false,
									"type": "number",
									"input": true,
									"key": "perc",
									"validate": {
										"customMessage": "",
										"json": "",
										"required": false,
										"custom": "",
										"customPrivate": false,
										"min": "",
										"max": "",
										"step": "any",
										"integer": ""
									},
									"conditional": {
										"show": "",
										"when": "",
										"json": "",
										"eq": ""
									},
									"delimiter": false,
									"requireDecimal": false,
									"encrypted": false,
									"properties": {},
									"customConditional": "",
									"logic": [],
									"attributes": {},
									"row": "0-2",
									"reorder": false
								}

							],
							"tab": 0,
							"encrypted": false,
							"properties": {},
							"customConditional": "",
							"logic": [],
							"attributes": {},
							"addAnother": "",
							"groupToggle": false,
							"placeholder": "",
							"prefix": "",
							"customClass": "",
							"suffix": "",
							"multiple": false,
							"protected": false,
							"unique": false,
							"persistent": true,
							"hidden": false,
							"clearOnHide": true,
							"dataGridLabel": false,
							"labelPosition": "top",
							"labelWidth": 30,
							"labelMargin": 3,
							"description": "",
							"errorLabel": "",
							"tooltip": "",
							"hideLabel": false,
							"tabindex": "",
							"disabled": false,
							"autofocus": false,
							"dbIndex": false,
							"customDefaultValue": "",
							"calculateValue": "",
							"allowCalculateOverride": false,
							"widget": null,
							"refreshOn": "",
							"clearOnRefresh": false,
							"validateOn": "change",
							"tree": true,
							"id": "elio60n"
						}
					]
				},
				{
					"label": "Defects",
					"key": "defects",
					"components": [
						{
							"label": "Defect Items",
							"reorder": false,
							"mask": false,
							"tableView": true,
							"alwaysEnabled": false,
							"type": "editgrid",
							"input": true,
							"key": "defectItems",
							"validate": {
								"customMessage": "",
								"json": ""
							},
							"conditional": {
								"show": "",
								"when": "",
								"json": ""
							},
							"components": [
								{
									"label": "Columns",
									"columns": [
										{
											"components": [
												{
													"label": "Equipment Nodes",
													"optionsLabelPosition": "right",
													"values": [
														{
															"label": "Rev 536",
															"value": "rev536",
															"shortcut": ""
														},
														{
															"label": "Rev 537",
															"value": "rev537",
															"shortcut": ""
														},
														{
															"label": "Rev 538",
															"value": "rev538",
															"shortcut": ""
														},
														{
															"label": "Rev 539",
															"value": "rev539",
															"shortcut": ""
														}
													],
													"inline": false,
													"mask": false,
													"tableView": true,
													"alwaysEnabled": false,
													"type": "radio",
													"input": true,
													"key": "nodes",
													"defaultValue": "rev536",
													"validate": {
														"customMessage": "",
														"json": ""
													},
													"conditional": {
														"show": "",
														"when": "",
														"json": ""
													},
													"encrypted": false,
													"properties": {},
													"customConditional": "",
													"logic": [],
													"attributes": {},
													"tags": [],
													"reorder": false
												}
											],
											"width": 4,
											"offset": 0,
											"push": 0,
											"pull": 0,
											"type": "column",
											"input": false,
											"hideOnChildrenHidden": false,
											"key": "column",
											"tableView": true,
											"label": "Column"
										},
										{
											"components": [
												{
													"label": "Defects",
													"optionsLabelPosition": "right",
													"values": [
														{
															"label": "Def 1",
															"value": "def1",
															"shortcut": ""
														},
														{
															"label": "Def 3",
															"value": "def3",
															"shortcut": ""
														},
														{
															"label": "Def 5",
															"value": "def5",
															"shortcut": ""
														},
														{
															"label": "Def 7",
															"value": "def7",
															"shortcut": ""
														}
													],
													"inline": false,
													"mask": false,
													"tableView": true,
													"alwaysEnabled": false,
													"type": "radio",
													"input": true,
													"key": "defects",
													"defaultValue": "def1",
													"validate": {
														"customMessage": "",
														"json": ""
													},
													"conditional": {
														"show": "",
														"when": "",
														"json": ""
													},
													"encrypted": false,
													"properties": {},
													"customConditional": "",
													"logic": [],
													"attributes": {},
													"tags": [],
													"reorder": false
												},
												{
													"label": "Additional Defects",
													"mask": false,
													"tableView": true,
													"alwaysEnabled": false,
													"type": "select",
													"input": true,
													"key": "additionalDefects",
													"defaultValue": "",
													"validate": {
														"select": false,
														"customMessage": "",
														"json": ""
													},
													"conditional": {
														"show": "",
														"when": "",
														"json": ""
													},
													"data": {
														"values": [
															{
																"label": "Def 4",
																"value": "def4"
															},
															{
																"label": "Def 8",
																"value": "def8"
															},
															{
																"label": "Def 15",
																"value": "def15"
															}
														]
													},
													"valueProperty": "value",
													"customConditional": "",
													"properties": {},
													"selectThreshold": 0.3,
													"encrypted": false,
													"reorder": false,
													"lazyLoad": false,
													"selectValues": "",
													"disableLimit": false,
													"sort": "",
													"reference": false,
													"logic": [],
													"attributes": {}
												}
											],
											"width": 4,
											"offset": 0,
											"push": 0,
											"pull": 0,
											"type": "column",
											"input": false,
											"hideOnChildrenHidden": false,
											"key": "column",
											"tableView": true,
											"label": "Column"
										},
										{
											"width": 4,
											"offset": 0,
											"push": 0,
											"pull": 0,
											"type": "column",
											"input": false,
											"hideOnChildrenHidden": false,
											"key": "column",
											"tableView": true,
											"label": "Column",
											"components": [
												{
													"label": "Defect Type",
													"optionsLabelPosition": "right",
													"values": [
														{
															"label": "Fix",
															"value": "fix",
															"shortcut": ""
														},
														{
															"label": "NoFix",
															"value": "noFix",
															"shortcut": ""
														}
													],
													"inline": false,
													"mask": false,
													"tableView": true,
													"alwaysEnabled": false,
													"type": "radio",
													"input": true,
													"key": "defectsTypes",
													"defaultValue": "fix",
													"validate": {
														"customMessage": "",
														"json": ""
													},
													"conditional": {
														"show": "",
														"when": "",
														"json": ""
													},
													"encrypted": false,
													"properties": {},
													"customConditional": "",
													"logic": [],
													"attributes": {},
													"tags": [],
													"reorder": false
												}
											]
										}
									],
									"mask": false,
									"tableView": false,
									"alwaysEnabled": false,
									"type": "columns",
									"input": false,
									"key": "columns3",
									"conditional": {
										"show": "",
										"when": "",
										"json": ""
									},
									"reorder": false,
									"properties": {},
									"customConditional": "",
									"logic": [],
									"attributes": {}
								}
							],
							"rowClass": "",
							"addAnother": "Add Defect",
							"modal": false,
							"saveRow": "",
							"encrypted": false,
							"properties": {},
							"customConditional": "",
							"logic": [],
							"attributes": {},
							"tab": 1,
							"tags": []
						}
					]
				},
				{
					"label": "Quality",
					"key": "quality",
					"components": [
						{
							"label": "Quality Characteristics",
							"reorder": false,
							"mask": false,
							"tableView": true,
							"alwaysEnabled": false,
							"type": "editgrid",
							"input": true,
							"key": "charact",
							"validate": {
								"customMessage": "",
								"json": "",
								"required": false,
								"custom": "",
								"customPrivate": false
							},
							"conditional": {
								"show": "",
								"when": "",
								"json": "",
								"eq": ""
							},
							"components": [
								{
									"label": "Diameter",
									"mask": false,
									"tableView": true,
									"alwaysEnabled": false,
									"type": "number",
									"input": true,
									"key": "diameter",
									"validate": {
										"customMessage": "",
										"json": "",
										"required": false,
										"custom": "",
										"customPrivate": false,
										"min": "",
										"max": "",
										"step": "any",
										"integer": ""
									},
									"conditional": {
										"show": "",
										"when": "",
										"json": "",
										"eq": ""
									},
									"reorder": false,
									"delimiter": false,
									"requireDecimal": false,
									"encrypted": false,
									"properties": {},
									"customConditional": "",
									"logic": [],
									"attributes": {},
									"placeholder": "",
									"prefix": "",
									"customClass": "",
									"suffix": "",
									"multiple": false,
									"defaultValue": null,
									"protected": false,
									"unique": false,
									"persistent": true,
									"hidden": false,
									"clearOnHide": true,
									"dataGridLabel": false,
									"labelPosition": "top",
									"labelWidth": 30,
									"labelMargin": 3,
									"description": "",
									"errorLabel": "",
									"tooltip": "",
									"hideLabel": false,
									"tabindex": "",
									"disabled": false,
									"autofocus": false,
									"dbIndex": false,
									"customDefaultValue": "",
									"calculateValue": "",
									"allowCalculateOverride": false,
									"widget": null,
									"refreshOn": "",
									"clearOnRefresh": false,
									"validateOn": "change",
									"id": "e8h22ub"
								},
								{
									"label": "Tolschina",
									"mask": false,
									"tableView": true,
									"alwaysEnabled": false,
									"type": "number",
									"input": true,
									"key": "tolschina",
									"validate": {
										"customMessage": "",
										"json": "",
										"required": false,
										"custom": "",
										"customPrivate": false,
										"min": "",
										"max": "",
										"step": "any",
										"integer": ""
									},
									"conditional": {
										"show": "",
										"when": "",
										"json": "",
										"eq": ""
									},
									"reorder": false,
									"delimiter": false,
									"requireDecimal": false,
									"encrypted": false,
									"properties": {},
									"customConditional": "",
									"logic": [],
									"attributes": {},
									"placeholder": "",
									"prefix": "",
									"customClass": "",
									"suffix": "",
									"multiple": false,
									"defaultValue": null,
									"protected": false,
									"unique": false,
									"persistent": true,
									"hidden": false,
									"clearOnHide": true,
									"dataGridLabel": false,
									"labelPosition": "top",
									"labelWidth": 30,
									"labelMargin": 3,
									"description": "",
									"errorLabel": "",
									"tooltip": "",
									"hideLabel": false,
									"tabindex": "",
									"disabled": false,
									"autofocus": false,
									"dbIndex": false,
									"customDefaultValue": "",
									"calculateValue": "",
									"allowCalculateOverride": false,
									"widget": null,
									"refreshOn": "",
									"clearOnRefresh": false,
									"validateOn": "change",
									"id": "e2qw0kp"
								},
								{
									"label": "Radio",
									"labelPosition": "left-left",
									"optionsLabelPosition": "right",
									"values": [
										{
											"label": "ok",
											"value": "ok",
											"shortcut": ""
										},
										{
											"label": "ne ok",
											"value": "neOk",
											"shortcut": ""
										},
										{
											"label": "ne ochen ok",
											"value": "neOchenOk",
											"shortcut": ""
										}
									],
									"inline": true,
									"mask": false,
									"tableView": true,
									"alwaysEnabled": false,
									"type": "radio",
									"input": true,
									"key": "radio",
									"defaultValue": "",
									"validate": {
										"customMessage": "",
										"json": "",
										"required": false,
										"custom": "",
										"customPrivate": false
									},
									"conditional": {
										"show": "",
										"when": "",
										"json": "",
										"eq": ""
									},
									"reorder": false,
									"encrypted": false,
									"properties": {},
									"customConditional": "",
									"logic": [],
									"attributes": {},
									"placeholder": "",
									"prefix": "",
									"customClass": "",
									"suffix": "",
									"multiple": false,
									"protected": false,
									"unique": false,
									"persistent": true,
									"hidden": false,
									"clearOnHide": true,
									"dataGridLabel": false,
									"labelWidth": 30,
									"labelMargin": 3,
									"description": "",
									"errorLabel": "",
									"tooltip": "",
									"hideLabel": false,
									"tabindex": "",
									"disabled": false,
									"autofocus": false,
									"dbIndex": false,
									"customDefaultValue": "",
									"calculateValue": "",
									"allowCalculateOverride": false,
									"widget": null,
									"refreshOn": "",
									"clearOnRefresh": false,
									"validateOn": "change",
									"inputType": "radio",
									"fieldSet": false,
									"id": "emm2lsb"
								}
							],
							"tab": 2,
							"rowClass": "",
							"addAnother": "",
							"modal": false,
							"saveRow": "",
							"encrypted": false,
							"properties": {},
							"customConditional": "",
							"logic": [],
							"attributes": {},
							"tags": [],
							"placeholder": "",
							"prefix": "",
							"customClass": "",
							"suffix": "",
							"multiple": false,
							"defaultValue": null,
							"protected": false,
							"unique": false,
							"persistent": true,
							"hidden": false,
							"clearOnHide": true,
							"dataGridLabel": false,
							"labelPosition": "top",
							"labelWidth": 30,
							"labelMargin": 3,
							"description": "",
							"errorLabel": "",
							"tooltip": "",
							"hideLabel": false,
							"tabindex": "",
							"disabled": false,
							"autofocus": false,
							"dbIndex": false,
							"customDefaultValue": "",
							"calculateValue": "",
							"allowCalculateOverride": false,
							"widget": null,
							"refreshOn": "",
							"clearOnRefresh": false,
							"validateOn": "change",
							"tree": true,
							"defaultOpen": false,
							"removeRow": "",
							"inlineEdit": false,
							"templates": {
								"header": "<div class=\"row\">\n  {% util.eachComponent(components, function(component) { %}\n    <div class=\"col-sm-2\">{{ component.label }}</div>\n  {% }) %}\n</div>",
								"row": "<div class=\"row\">\n  {% util.eachComponent(components, function(component) { %}\n    <div class=\"col-sm-2\">\n      {{ getView(component, row[component.key]) }}\n    </div>\n  {% }) %}\n  {% if (!instance.options.readOnly) { %}\n    <div class=\"col-sm-2\">\n      <div class=\"btn-group pull-right\">\n        <button class=\"btn btn-default btn-sm editRow\">Edit</button>\n        <button class=\"btn btn-danger btn-sm removeRow\">Delete</button>\n      </div>\n    </div>\n  {% } %}\n</div>",
								"footer": ""
							},
							"id": "e00vjx5"
						}
					]
				}
			],
			"mask": false,
			"tableView": true,
			"alwaysEnabled": false,
			"type": "tabs",
			"input": false,
			"key": "tabs2",
			"conditional": {
				"show": "",
				"when": "",
				"json": ""
			},
			"properties": {},
			"customConditional": "",
			"logic": [],
			"attributes": {},
			"reorder": false
		},
		{
			"type": "button",
			"label": "Submit",
			"key": "submit",
			"disableOnInvalid": true,
			"theme": "primary",
			"input": true,
			"tableView": true
		}
	]
}


    return { myform: myform }
    },
  name: "mes-form-builder",
  components:  { formio: Form },
  computed:{
  },
  methods: {
    onSubmit(){
      console.log('Worked')
    }
  }
}
</script>

<style scoped lang="scss">
.formio-container /deep/ {
  @import "~bootstrap/dist/css/bootstrap.min";
}
</style>
