mutation($resourceId:String!){
  purchasesMutation{
    addToCart(resourceId:$resourceId){
      id,resource{id,name,resourceGroup{id,name}},measurementUnit{id,name},resourceName,quantity,dateDelivery
    }
  }
}