query ($id: ID) {
	purchases {
        resource (id: $id){
            id,
            fullName,
            name,
            designation,
            measurementUnit{
                shortName,
                fullName
            }
            resourceGroup{
                id,
                name
            }
        }
    }
}