query($group: String){
	purchases{
        items:resourcesGroup(group:$group){
            id, name,children{id,name, children{id,name} }, 
            resources{id,name,designation}
        }
    }
}