query($id:ID!){
	purchases {
    resources (id: $id){
    id,
    fullName,
    name,
    designation,
    measurementUnit{shortName,fullName}
    resourceGroup{
            id,
            name
        }
    }
}
}