query allMaintenanceNorms($after: String, $first: Int, $where: [WhereExpressionGraph], $orderBy: [OrderByGraph], $ids: [ID]) {
  eamQuery {
    maintenanceNormsConnection(after: $after, first: $first, where: $where, orderBy: $orderBy, ids: $ids) {
      edges {
        node {
          id
          techRouteDesignation
          resource {
            id
            name
          }
          direction {
            id
            name
          }
          repairType {
            id
            name
          }          
          isValid        
          periodicity
          periodType          
          maintenanceNormType
          duration
          exactDuration
        }
      }
      totalCount
      pageInfo {
        hasNextPage
        hasPreviousPage
        startCursor
        endCursor
      }
    }
  }
}