query allWorkRequests($after: String, $first: Int, $where: [WhereExpressionGraph], $orderBy: [OrderByGraph], $ids: [ID], $search: String) {
	eam {
		workRequestConnection(after: $after, first: $first, where: $where, orderBy: $orderBy, ids: $ids, search: $search) {
			edges {
				node {
					id
					creationDate
					equipment {
						id
						name
						fullName
					}
					technicalPlace {
						id
						name
					}
					department {
						id
						name
					}
					content

					declarerEmployee {
						id
						fullName
					}
					responsibleEmployee {
						id
						fullName
					}
					performerEmployee {
						id
						fullName
					}
					category {
						id
						name
					}
					direction {
						id
						name
					}
					repairType {
						id
						name
					}
					workRequestCategoryId
					source
					status
					isValid
				}
			}
			totalCount
			pageInfo {
				hasNextPage
				hasPreviousPage
				startCursor
				endCursor
			}
		}
	}
}