query allInspectionsByEquipment($after: String, $first: Int, $where: [WhereExpressionGraph], $orderBy:[OrderByGraph], $ids: [ID], $equipmentId: String ) {
  eamQuery {
    conditionParameterByEquipmentValuesConnection(after: $after, first: $first, where: $where, orderBy: $orderBy, ids: $ids, equipmentId:$equipmentId) {
      edges {
        node {
          id
          date  
          conditionParameter{
            id
            name
            measurementUnit{
              id
              name
            }
            maxValue
            minValue
            valueRanges {
              id
              description
              minValue
              maxValue
              workRequestCategoryId
            }
            valueInputType
          }          
          equipment {
            id
            name
            fullName
          }
          technicalPlace {
            id
            name
          }
          department {
            id
            name
          }
          description
          comment          
          value
          isClosed
          additionalData{            
            failureReason{id name}
            failureType{id name}            
            responsible{id fullName}
            isValid
          }
          attachments {
            id
          }
        }
      }
      totalCount
      pageInfo {
        hasNextPage
        hasPreviousPage
        startCursor
        endCursor
      }
    }
  }
}