query equipmentImages($id: ID) {
  eamQuery {
    equipment(id: $id) {
      id
      images {
        id
        fileName
        url
      }
      model {
        id
        attachments {
          id
          fileName
          url
        }
      }
    }
  }
}