mutation($alias:String!,$keyValue:String! , $listId:String!){
          purchasesMutation{
            addToFavoritesOne(alias:$alias, keyValue:$keyValue, listId:$listId){
              id,
              keyValue,
              list{
                id, alias, keyValues, caption, isDefaultList
              }
            }
          }
        }