

mutation($keyValue:String!, $newFavListId: String!, $oldFavListId : String!){
  purchasesMutation{
    mutationChangeListForItem(keyValue:$keyValue, newFavListId:$newFavListId, oldFavListId:$oldFavListId)
  }
}