query equipmentTypes($take:Int, $where: [WhereExpressionGraph], $orderBy: [OrderByGraph], $ids: [ID]) {
  eamQuery {
    equipmentTypes(take:$take, where: $where, orderBy: $orderBy, ids: $ids) {
      id
      name
    }
  }
}