query singleDowntime($id: ID) {
  eamQuery {
    downTimes(id: $id) {
      id
      date
      endDate
      equipment {
        id
        name
        fullName
      }
      technicalPlace {
        id
        name
      }
      department {
        id
        name
      }
      equipmentModel {
        id
        name
      }
      description
      comment
      value
      additionalData {
        direction {
          id
          name
        }
        downTimeType
        failureReason {
          id
          name
        }
        failureType {
          id
          name
        }
        isEmergency
        isPlanned
        sourceTechPlace {
          id
          name
        }
        responsible {
          id
          fullName
        }
      }
    }
  }
}
