query unclassifiedDownTimes($after: String, $first: Int, $where: [WhereExpressionGraph], $orderBy: [OrderByGraph], $ids: [ID], $search: String) {
  eam {
    unclassifiedDownTimesConnection(after: $after, first: $first, where: $where, orderBy: $orderBy, ids: $ids, search: $search) {
      edges {
        node {
          id
          date
          endDate
          equipment {
            id
            name
            fullName
          }
          technicalPlace {
            id
            name
          }
          department {
            id
            name
          }
          description
          comment
          value
          additionalData{
            direction{ id name }
            downTimeType
            failureReason{ id name }
            failureType{ id name }
            isEmergency
            isPlanned
            sourceTechPlace{ id name }
            responsible{ id fullName }
          }
        }
      }
      totalCount
      pageInfo {
        hasNextPage
        hasPreviousPage
        startCursor
        endCursor
      }
    }
  }
}