import Vue from 'vue'
import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faTasks,
  faSuitcase,
  faProjectDiagram,
  faFolder,
  faFolderOpen,
  faMoneyCheckEdit,
  faChalkboardTeacher,
  faCommentAltDots,
  faPaperclip,
  faRecycle,
  faExclamationCircle,
  faCheckCircle,
  faFileSearch,
  faTimes,
  faExclamationSquare,
  faEye,
  faCommentAltLines,
  faHorizontalRule,
  faTrash,
  faUsers,
  faMailBulk,
  faSearch,
  faChevronRight,
  faBars,
  faUser,
  faAt,
  faUserTag,
  faSignOutAlt,
  faFileAlt,
  faSync,
  faMedal,
  faBorderAll,
  faCheck,
  faLayerPlus,
  faEdit,
  faDownload,
  faClock,
  faPaperPlane,
  faSearchPlus,
  faSearchMinus,
  faCompressArrowsAlt,
  faCompress,
  faArrowAltLeft,
  faFlag,
  faClipboardCheck,
  faUndo,
  faThumbsUp,
  faArrowAltRight,
  faStar,
  faSitemap,
  faFolderTree,
  faEllipsisV,
  faListAlt,
  faTable,
  faFire,
  faHourglass,
  faCheckDouble,
  faReply
} from '@fortawesome/pro-regular-svg-icons'
import {
  faFilesMedical as falFilesMedical,
  faArrowAltDown as falArrowAltDown,
  faTrash as falTrash,
  faTimes as falTimes,
  faCheck as falCheck,
  faExclamation as falExclamation,
  faDownload as falDownload,
  faCalendarDay as falCalendarDay,
  faUser as falUser,
  faSave as falSave
} from '@fortawesome/pro-light-svg-icons'
import FaIcon from '@/components/FaIcon'

library.add(
  faTasks,
  faSuitcase,
  faProjectDiagram,
  faFolder,
  faFolderOpen,
  faMoneyCheckEdit,
  faChalkboardTeacher,
  faCommentAltDots,
  faPaperclip,
  faRecycle,
  faExclamationCircle,
  faCheckCircle,
  faFileSearch,
  faTimes,
  faExclamationSquare,
  faEye,
  faCommentAltLines,
  faHorizontalRule,
  faTrash,
  faUsers,
  faMailBulk,
  faSearch,
  faChevronRight,
  faBars,
  faUser,
  faAt,
  faUserTag,
  faSignOutAlt,
  faFileAlt,
  faSync,
  faMedal,
  faBorderAll,
  faCheck,
  faLayerPlus,
  faEdit,
  faDownload,
  faClock,
  faPaperPlane,
  faSearchPlus,
  faSearchMinus,
  faCompressArrowsAlt,
  faCompress,
  faArrowAltLeft,
  faFlag,
  faClipboardCheck,
  faUndo,
  faThumbsUp,
  faArrowAltRight,
  faStar,
  faSitemap,
  faFolderTree,
  faEllipsisV,
  faListAlt,
  faTable,
  faFire,
  faHourglass,
  faCheckDouble,
  faReply,
  falFilesMedical,
  falArrowAltDown,
  falTrash,
  falTimes,
  falCheck,
  falArrowAltDown,
  falExclamation,
  falDownload,
  falCalendarDay,
  falUser,
  falSave)

Vue.component('fa-icon', FaIcon)
