query allEfficiencyLosses($after: String, $first: Int, $where: [WhereExpressionGraph], $orderBy: [OrderByGraph], $ids: [ID]) {
  efficiencyQuery {
    efficiencyLossesConnection(after: $after, first: $first, where: $where, orderBy: $orderBy, ids: $ids) {
      edges {
        node {
          id
          workCenter {
            id
            name
          }
          technicalPlace {
            id
            name
          }
          startTime
          endTime
          lossType
          indicator
          category {
            id
            name
          }
          reason {
            id
            name
          }
          source {
            id
            name
          }
          lossLevel
          isApproved
          isValid
        }
      }
      totalCount
      pageInfo {
        hasNextPage
        hasPreviousPage
        startCursor
        endCursor
      }
    }
  }
}
